"use client";
import React, { useEffect, useState } from "react";

import Image from "next/image";

import Head from "next/head";

import axios from "axios";
import { BaseURl } from "@/utils/config";
import { MDXRemote, MDXRemoteSerializeResult } from "next-mdx-remote/rsc";
import Comments from "@/components/Comments";

const DetailsPage = ({ params }: any) => {
  const [post, setPost]: any = useState([]);
  useEffect(() => {
    axios({
      method: "get",
      url: `${BaseURl}api/blog/getsingle/${params.slug}`,
    })
      .then((res) => {
        setPost(res.data.data);
        // console.log("ressssss", res);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);

  let img = post?.imageThumb;
  return (
    <>
      <Head>
        <title>{post?.title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta
          name="description"
          content="Tech blog, HTML, CSS, JavaScript, React.js, technology tutorials, web development, coding, programming, software development"
        ></meta>

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" single-article  bg-backgroundColor   dark:text-white   mx-5 my-8  border-r-2 border-b-2 lg:flex-row md:flex-row sm:flex-col xs:flex-col  flex  gap-2 ">
        <div className=" lg:w-[70%] md:w-[70%]  m-auto sm:w-full  xs:w-full bg-white   rounded-md shadow-sm p-3">
          <h1 className="text-3xl font-bold py-2  ">
            {post?.title}
            {/* hello word this is new world */}
          </h1>
          <div className="flex items-center my-4 justify-between border-y-2 p-2">
            <div>
              <div className=" overflow-hidden flex gap-2 items-center justify-center ">
                <Image
                  src="/user-profile.png"
                  alt="no"
                  // src={`http://localhost:1337${article.attributes.author.data.attributes.avatar.data.attributes.formats.thumbnail.url}`}
                  height={40}
                  width={40}
                />
                <span className="text-sm font-bold text-gray-600">
                  {/* {article.attributes.author.data.attributes.firstname}{" "} */}
                  buggplayer
                  {/* {article.attributes.author.data.attributes.lastname} on &nbsp; */}
                  <span className="text-gray-400 ml-1">
                    {/* {formatDate(article.attributes.createdAt)} */}
                    23 aug 23
                  </span>
                </span>
              </div>
            </div>

            <div className=" flex gap-3 mr-5">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                className="w-6 h-6"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z"
                />
              </svg>

              <a className="hover:text-gray-400 cursor-pointer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"
                  />
                </svg>
              </a>
              <a
                onClick={() =>
                  navigator.clipboard.writeText(
                    `https://www.techblogging.in/${params.slug}`
                  )
                }
                className="hover:text-gray-400 cursor-pointer"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M7.217 10.907a2.25 2.25 0 100 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186l9.566-5.314m-9.566 7.5l9.566 5.314m0 0a2.25 2.25 0 103.935 2.186 2.25 2.25 0 00-3.935-2.186zm0-12.814a2.25 2.25 0 103.933-2.185 2.25 2.25 0 00-3.933 2.185z"
                  />
                </svg>
              </a>
            </div>
          </div>

          <div className="text-lg text-gray-600 leading-8">

            <Image
              // className="w-[70%] m-auto my-6 mb-6"
              // src="/img2.jpg"
              alt="no alt"
              // src="/desk.jpg"
              height={300}
              width={300}
              src={img || "/desk.jpg"}
              // alt={post.title}
            />
            
            <div
              className="text-subHeadingTextColor text-sm  break-words   py-2"
              dangerouslySetInnerHTML={{ __html: post.content }}
            />
          </div>
        </div>
        {/* <div className=" lg:w-[30%] md:w-[30%] sm:w-full xs:w-full sticky top-0 text-center  p-3   ">
          <div className="bg-white rounded-md p-3 ">
            <h2 className="font-bold  text-lg ">Signup to our newsletter</h2>
            <p className="mt-4 text-gray-500">
              Get the latest article on all things data delivered straight to
              your inbox
            </p>
            <input
              className="border  p-2 pl-3 my-6 outline-primary"
              type="email"
              placeholder="Your work email"
            />
            <button className="border-2 border-primary rounded py-1 px-6 text-primary font-bold">
              Subscribe
            </button>
            <hr className="my-6 border-gray-100" />
            <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
              <span className="text-gray-500 mr-2">Share</span>
              <a className="text-gray-500">
                <svg
                  fill="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500">
                <svg
                  fill="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500">
                <svg
                  fill="none"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500">
                <svg
                  fill="currentColor"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="0"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke="none"
                    d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
                  ></path>
                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                </svg>
              </a>
            </span>
            <hr className="my-6 border-gray-100" />
          </div>
        </div> */}
      </div>
      {/* <div className="bg-white shadow-md m-4">
        <Comments />
      </div> */}
    </>
  );
};

export default DetailsPage;
