import React from "react";
import { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { capitalizeFirstLetter, debounce, makeCategory } from "@/utils/utils";
import Tabs from "@/components/Tabs";
import ArticleList from "@/components/ArticleList";

const Category = ({ categories, articles, slug }: any) => {
  const router = useRouter();
  const { category: categorySlug } = router.query;

  const formattedCategory = () => {
    return capitalizeFirstLetter(makeCategory(slug));
  };

  const handleSearch = (query: string) => {
    router.push(`/category/${categorySlug}/?search=${query}`);
  };

  return (
    <>
      <Head>
        <title>Tech Blog {formattedCategory()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs
        categories={categories.items}
        handleOnSearch={debounce(handleSearch, 500)}
      />
      <ArticleList articles={articles.items} />
    </>
  );
};


export default Category;
