import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // suppressHydrationWarning
  return (
    <html lang="en">
      <body
        className={` ${inter.className} mb-32  bg-backgroundColor text-headingTextColor
         dark:bg-gray-900 
         dark:selection:bg-gray-900 
          dark:text-white 
           selection:bg-gray-50
           `}
      >
        <Navbar />
        <main className=" ">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
