import Navbar from "@/components/Navbar";
import Image from "next/image";

import type { AppProps } from "next/app";

import Tabs from "@/components/Tabs";
import Head from "next/head";
import ArticleList from "@/components/ArticleList";

export default function Home({ Component, pageProps }: AppProps) {
  const staticArticle = [
    {
      id: 1,
      first_name: "Jeanette",
      last_name: "Penddreth",
      title: "What's a Blog & Why You Need One",
      email: "jpenddreth0@census.gov",
      gender: "Female",
      ip_address: "26.58.193.2",
    },
    {
      id: 2,
      first_name: "Giavani",
      last_name: "Frediani",
      email: "gfrediani1@senate.gov",
      title: "What's a Blog & Why You Need One",
      gender: "Male",
      ip_address: "229.179.4.212",
    },
    {
      id: 3,
      first_name: "Noell",
      last_name: "Bea",
      title: "What's a Blog & Why You Need One",
      email: "nbea2@imageshack.us",
      gender: "Female",
      ip_address: "180.66.162.255",
    },
    {
      id: 4,
      first_name: "Willard",
      last_name: "Valek",
      title: "What's a Blog & Why You Need One",
      email: "wvalek3@vk.com",
      gender: "Male",
      ip_address: "67.76.188.26",
    },
  ];
  return (
    <main className=" p-6 pb-32  mx-auto font-sans ">
      <div className="h-screen">
        <Head>
          <title>Tech's Blog Homepage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Tabs
        // categories={categories.items}
        // handleOnSearch={debounce(handleSearch, 500)}
        />
        <ArticleList
         articles={staticArticle}
        />
        {/* <Pagination
             page={page} pageCount={pageCount}
              /> */}
      </div>
    </main>
  );
}
